### STATUS 200
GET localhost:8083/api/token/issue_tokens?user_id=12
Content-Type: application/json

### STATUS 200
PUT localhost:8083/api/token/update_tokens
Content-Type: application/json

{
  "access_token": "y4ZIIv1dCrfn0Xx7qIqUTIkEyLBJ7tB3lU5riuvZiuYT8fVxM4nwtGDrBTpc6gCbkZh+rcTwSJvDTdehT+AJFPAz6h+yuWeBlKr+OJR+dVq2ZU4GebFf9U65vK7LrOQdju59bSQ8ehffsOXFnPS01yI6VVE8sfI8H70pvusA6CZMttMT9SkdT3Bj/7GPxvyMPrfOHn6w8xI5/u837yyAYrDw6Cp0Pa/EFX+6i/trSfhHkI2ESNleZAQkDQmu6eVh0IRHHe6r5pVh+c6fThqQAYQqyLui/gClyHZcoz04QLK59Www8pM0X1jW47KnJJM02gRR8ZpkIvm/JNk6mdoAB++GEaZxzeRdeveoRjKz7GlxsxwhX3r6AZIqDVNK4dOM7lPK7UhMQdAAHWih0rQnCm6NF27bNUKuCfS+/xLgZGlk3FPitR+kEkDW3c/ENgAaatG0SmjdewfG49kDtWhQAtGVHPzEU/a5E4Av2zXOIuCc5Hx4V/N25ehNDiV6RUob02cNoPbuOtf9eNa+GXoMootdgkVsM/SuWKYtaldmSwU/+OR/5AQ7MTrnBDK5VjP6s6UsqAd9SPpnp3AS7mmeM9EPmXYolg8fjktsc4hwMITwLV0ZlPJGcnSAkSTGG3t7JTzqqSQ7AOtRBp5PQYgq4QZBJqQzgMjY8C4TYQF3qax5h4X6z0cmGYAXf6p2HMc2L5xDI6gS1nTydmo36/wYqpwDFDg5R2umqvgo0N5U0mvhYu+qlAW+uSLmY63m0FPM5PzmLbWRyWCmNO8ZtxqCQwjGoKiHy7s2KUEkYVZwgtd11drbr5rgqcSd2WgpCiz6S/lxscSpxHRWY5Ptu2C7Xzve56sMrsjysnOfmFYtvfY7wJgc9T3A1HfIZ7YA77NqjXg9BzvjS5hyYSHI",
  "refresh_token": "ttFj7RTiEUHwicUX3Ywf3NDiUT5QrXjXg0mUf+jApUH783ltgXzISChQNYz1Zzt1J/vMDj0r24F91XQxOpUqWfNvgnHfwG+tTm2Q7qjFQwiIJX2KETJEjdSh7OqU3NfbRCOKEcfVlGaCq8kfvb4s0T9XjaxbqIu8aSt+n9ty7xEwTZB+TufsW3nat4ceZoPsqXZ7pBTjPV9lfD78Fy2nZyoboNyjhAjJ00M10kSHb2Rg12t2ltr8d0aWqw=="
}

### STATUS 200
GET localhost:8083/api/token/get_user
Content-Type: application/json

{
  "access_token": "YSvsVr73inbzmfS4wJWmWyrx3jZgxTTdPUKZpxFPKF+rz+Nneye5VgNstOHiXn4TCnFLwaDbL/NL9agsq1U2fXalFH5lI5oySL5Ho7oDeVV7QU3xzvrdmjloA3TBpDVzBNVO1U/KimnJiJLXO4Uhe8necstlzuCDHnXeL4rGC+BKH/N0j1x10HNIkJ3hdB3H744tNuY2rdvAnot7Z/BRyNqA8+m7UsgML2lMzZ3wN8E+8lUCq0+seV9X+0k4je1JBAz7OaQV6q3nPUUfoXj5MwVKrJE9TXYtB03eIhnjcJDjkSNAYa8H/jijluTQ+lmebq3X8kEfL3o3rkyeXOiUDSJkNmsvClVEoKMsVaGZZaYnvPX+RELV2nhCTD4b3z8EWsAvTQ5WtQJv2ifD8nqj5zeN8EtDCUjPkxpjIf2jtUjE0UvlOygBu1AVVmm7GnZIRIqxdTQqactrANCESWf5yXI35Cta/9pwhn1VSfENX1s7HOWDtNfr0Psr+XUC4ULzz2VKAI0reMzDW9wR0Sy7ru2bElVF2eLdQ615XU8oa07xYeCk8tzMS4HiB+5NAyJB+5b93g68wunhzKqQ8YKeONRIu1l4JSJ8QccedivjxVRq3BOjmRwVetf3n5FHAhIPx0S2vCxjTXHn+/JDj8hQguFSOl4jKoZZEe1D0xj4KSjLQGGdsV7/AqgURbWAg/BoQhzvjYoAMCorbaNrtDLsRo/yvgSrDOl/cWdla25VNgsGrn83UXl4JC3nlTPMfBsG/WvJedYfBdyRWTUia5sT5C/qaBGkRnWJvZPWNzm9kaV1HMwUEVDO1qX08KsA+jSDvzJnixnsCEb22uDaThk++DkvYa+c/Yb93+GTi8Fc7o77TlgzSrURt2hlrJkjHCjJlh7BTD2mNBjRf2f+"
}

### STATUS 200
POST localhost:8083/api/token/logout
Content-Type: application/json

{
  "access_token": "YSvsVr73inbzmfS4wJWmWyrx3jZgxTTdPUKZpxFPKF+rz+Nneye5VgNstOHiXn4TCnFLwaDbL/NL9agsq1U2fXalFH5lI5oySL5Ho7oDeVV7QU3xzvrdmjloA3TBpDVzBNVO1U/KimnJiJLXO4Uhe8necstlzuCDHnXeL4rGC+BKH/N0j1x10HNIkJ3hdB3H744tNuY2rdvAnot7Z/BRyNqA8+m7UsgML2lMzZ3wN8E+8lUCq0+seV9X+0k4je1JBAz7OaQV6q3nPUUfoXj5MwVKrJE9TXYtB03eIhnjcJDjkSNAYa8H/jijluTQ+lmebq3X8kEfL3o3rkyeXOiUDSJkNmsvClVEoKMsVaGZZaYnvPX+RELV2nhCTD4b3z8EWsAvTQ5WtQJv2ifD8nqj5zeN8EtDCUjPkxpjIf2jtUjE0UvlOygBu1AVVmm7GnZIRIqxdTQqactrANCESWf5yXI35Cta/9pwhn1VSfENX1s7HOWDtNfr0Psr+XUC4ULzz2VKAI0reMzDW9wR0Sy7ru2bElVF2eLdQ615XU8oa07xYeCk8tzMS4HiB+5NAyJB+5b93g68wunhzKqQ8YKeONRIu1l4JSJ8QccedivjxVRq3BOjmRwVetf3n5FHAhIPx0S2vCxjTXHn+/JDj8hQguFSOl4jKoZZEe1D0xj4KSjLQGGdsV7/AqgURbWAg/BoQhzvjYoAMCorbaNrtDLsRo/yvgSrDOl/cWdla25VNgsGrn83UXl4JC3nlTPMfBsG/WvJedYfBdyRWTUia5sT5C/qaBGkRnWJvZPWNzm9kaV1HMwUEVDO1qX08KsA+jSDvzJnixnsCEb22uDaThk++DkvYa+c/Yb93+GTi8Fc7o77TlgzSrURt2hlrJkjHCjJlh7BTD2mNBjRf2f+"
}
