### STATUS 200
GET localhost:8083/api/token/issue_tokens?user_id=12
Content-Type: application/json

### STATUS 200
PUT localhost:8083/api/token/update_tokens
Content-Type: application/json

{
  "access_token": "3kzuCue9QKvtstaZDF5sN9cQuel/6WVlTfHNZF9UWOGLOS8WHj0N48JQbrbJHWvBU6kfkH8JUv7PlIWkdyqZ+A2N5KubgitsHOmYXd1l6Id9MHdxaohQz4BU1AcaqYcjqzoGrN6h9T7qklnpTtPnmoqWL8c7KyqZsjuIKqsVZ11536EKrXA9UMqjJGt2B6bUrGVlpfMtz49LLn0fqGbOiRmAaAn3k/8kJJQBCzF13XC+Lx9KvQuBpxmqrW/kyDJuWk9zhjaFuTTDH2EA0gHMjZYPoXLW6uH3GMKNlIMKj7yZvY6BGX3WoupkO+eVlVhUGUNV303dRhPUDtmE+BsVUNaO4pDrTe+7wwVcfEXb1LQsdQjkPfdlDnayr2HiZ5+9lNr0ERPgts4roEFExmrSL8EMbHNKT4vt5nALMdf0aLOipG17Lq7qFxsWF1jnRe37ZUlF27kKGIpeRlNX/8sOxCA+jG24LPoJ7jk4MUbGjpTb0EAc02k6pUvwBbZ/PhIhwCbKOG5oXYQQaT5tlX+QvRTrcnmO5cklqHRFs9rQ8wUkPRlsJF0TiAbOAY2DyMhlWdrxKss6oQm+OlUciabtiJ4rvAzHBi3eTN5IzUNQGoNGAp7r8c+/nfCxzAWysBP2KAo9HGYt4Y7SyEmaImhwOVEMJGXwYdqhkyY0GpPisgSS9d7FgDI7VyJ/5O3srJFwHCBWZpI2uJHaGe/XSz1SpV0NiLG/cFLlZ6m6+BFzoPBTUKpaPjGsSAd0kWjuWhksRrjdy/45TCtF/AfPdRPlvFuKxFLAu0+bXMpabjxb92hx5soK4CtjOHFJGniPn7ntDF3XslXBWuiIWY9olhv/SNFzPtnS9KEIyVmBjOueQLpusnTAQrTRa4KvvemEjiypvMYz+ZYHBca98x7G",
  "refresh_token": "Gx5i5+tiVIDP+t9yNFtpI+TjWrMBQMi9V3UWnECjjD08FIHTR5sjwuvP/dNdX6ck5aCSL0LJQCLyh3zCpMTRK4bNOrUCwQEsvMZo7rKvfxfgZ2/+DBHObUCla4WnzFtg4VIT9PYY24dv16ZycfbdQg1GJhnp64VJHYQOqX8MCuiQsNtD5nvINyBWaQ1+s6Ad1WPQC8VpCKg+mNG+oTSkMKLf3ovtpckGB8YwzCU/4lxACpYCWZGqk6gsMw=="
}

### STATUS 200
GET localhost:8083/api/token/get_user
Content-Type: application/json

{
  "access_token": "YSvsVr73inbzmfS4wJWmWyrx2jZgxTTdPUKZpxFPKF+rz+Nneye5VgNstOHiXn4TCnFLwaDbL/NL9agsq1U2fXalFH5lI5oySL5Ho7oDeVV7QU3xzvrdmjloA3TBpDVzBNVO1U/KimnJiJLXO4Uhe8necstlzuCDHnXeL4rGC+BKH/N0j1x10HNIkJ3hdB3H744tNuY2rdvAnot7Z/BRyNqA8+m7UsgML2lMzZ3wN8E+8lUCq0+seV9X+0k4je1JBAz7OaQV6q3nPUUfoXj5MwVKrJE9TXYtB03eIhnjcJDjkSNAYa8H/jijluTQ+lmebq3X8kEfL3o3rkyeXOiUDSJkNmsvClVEoKMsVaGZZaYnvPX+RELV2nhCTD4b3z8EWsAvTQ5WtQJv2ifD8nqj5zeN8EtDCUjPkxpjIf2jtUjE0UvlOygBu1AVVmm7GnZIRIqxdTQqactrANCESWf5yXI35Cta/9pwhn1VSfENX1s7HOWDtNfr0Psr+XUC4ULzz2VKAI0reMzDW9wR0Sy7ru2bElVF2eLdQ615XU8oa07xYeCk8tzMS4HiB+5NAyJB+5b93g68wunhzKqQ8YKeONRIu1l4JSJ8QccedivjxVRq3BOjmRwVetf3n5FHAhIPx0S2vCxjTXHn+/JDj8hQguFSOl4jKoZZEe1D0xj4KSjLQGGdsV7/AqgURbWAg/BoQhzvjYoAMCorbaNrtDLsRo/yvgSrDOl/cWdla25VNgsGrn83UXl4JC3nlTPMfBsG/WvJedYfBdyRWTUia5sT5C/qaBGkRnWJvZPWNzm9kaV1HMwUEVDO1qX08KsA+jSDvzJnixnsCEb22uDaThk++DkvYa+c/Yb93+GTi8Fc7o77TlgzSrURt2hlrJkjHCjJlh7BTD2mNBjRf2f+"
}

### STATUS 200
POST localhost:8083/api/token/logout
Content-Type: application/json

{
  "access_token": "3kzuCue9QKvtstaZDF5sN9cQuel/6WVlTfHNZF9UWOGLOS8WHj0N48JQbrbJHWvBU6kfkH8JUv7PlIWkdyqZ+A2N5KubgitsHOmYXd1l6Id9MHdxaohQz4BU1AcaqYcjqzoGrN6h9T7qklnpTtPnmoqWL8c7KyqZsjuIKqsVZ11536EKrXA9UMqjJGt2B6bUrGVlpfMtz49LLn0fqGbOiRmAaAn3k/8kJJQBCzF13XC+Lx9KvQuBpxmqrW/kyDJuWk9zhjaFuTTDH2EA0gHMjZYPoXLW6uH3GMKNlIMKj7yZvY6BGX3WoupkO+eVlVhUGUNV303dRhPUDtmE+BsVUNaO4pDrTe+7wwVcfEXb1LQsdQjkPfdlDnayr2HiZ5+9lNr0ERPgts4roEFExmrSL8EMbHNKT4vt5nALMdf0aLOipG17Lq7qFxsWF1jnRe37ZUlF27kKGIpeRlNX/8sOxCA+jG24LPoJ7jk4MUbGjpTb0EAc02k6pUvwBbZ/PhIhwCbKOG5oXYQQaT5tlX+QvRTrcnmO5cklqHRFs9rQ8wUkPRlsJF0TiAbOAY2DyMhlWdrxKss6oQm+OlUciabtiJ4rvAzHBi3eTN5IzUNQGoNGAp7r8c+/nfCxzAWysBP2KAo9HGYt4Y7SyEmaImhwOVEMJGXwYdqhkyY0GpPisgSS9d7FgDI7VyJ/5O3srJFwHCBWZpI2uJHaGe/XSz1SpV0NiLG/cFLlZ6m6+BFzoPBTUKpaPjGsSAd0kWjuWhksRrjdy/45TCtF/AfPdRPlvFuKxFLAu0+bXMpabjxb92hx5soK4CtjOHFJGniPn7ntDF3XslXBWuiIWY9olhv/SNFzPtnS9KEIyVmBjOueQLpusnTAQrTRa4KvvemEjiypvMYz+ZYHBca98x7G"
  }