### STATUS 200
GET localhost:8083/api/token/issue_tokens?user_id=12
Content-Type: application/json

### STATUS 200
PUT localhost:8083/api/token/update_tokens
Content-Type: application/json

{
  "access_token": "dSiyp0mbfno/9BlvwxsX6m4Xnoc6nSXuQE5OTtbkZ2rr26CkKsU9yk7XJnfsAmrPRRj9sr2Hhq0J2+g+2EGBOUYesaYiZ/0v/7qmsi6jK5M7nE2A+jPZg+MXW7TGi7em73KTVFZGYZ21nhc4URRfnZ1gqtcUBtTGXG9bHFOjsVwSV1b661cUS0w2Kd6fPg4CqLbViMLN2WIiOixcNq95tHAvZrVjOmjtywQXSh0V3XOOdvCwPBm3y8RKJ70W0M11MitHqQvhXkRzZykdAYoUtlWjEYI7wWU5c+fmtDLohH7fK/TbukXJn5VEPlWfXYTAs3oRrbt+FQF3VY1wy1jVS7Q/PvXdzsy1R6DSF7h2HEFS+evrryNsEdazObsBWTJ3w40o0QFOwj9aZJtoz5jMWUPCWYNFhiI8Nd3vJwKCaiQNQvtWmRvaIeAKYCPtdyCZfS7bI4cuzPsFNcUi93qwtSR0+UBXAv5w7l7yvlX+G9pff88TTGUynjex/y3eRvbZdExzEE0XQrRawbxCHHsZ1B1fevQk8AdwL/1bYzcroNuluyleomZQHh2lQ/ECvDLxlD7/K5NF7fgSclIHSfb4gFkbd2fos0e8zVAk45V2SOeor0uXdtF1WedcN4TKCNj+zBjlneCd0svPEYLMWM9SgivlumpqHK+pTRWyg7RhUAssPZ9RgGpIAGf2fA6e8aMME5h9ozVkdkugO/yoFCvgyteCl2/KVBgs+j5i9odSdJYHwvXLhzWZAA3JIwpZVTV8yR8N889a7SJVpI6zR/woAa8XSvKy9KG13G2lI4npqP3dNfjbsNOOFCRU9Wrd3W2N4OpmoFVDCJROFpvFTkzgyOiYCxh1sGLMi/nQ+6fq9ATzF4iNOn+lSYzY1mO6I2AuibJLBLWYBqkdI8GH",
  "refresh_token": "2CXXLzAtM9ZnyRhZMuxIU9jdW+DzCXWAvDF8dVjMALy36RaFl4EugHydC6ojEOlVe1ytVfswdZmKlvTfchoqDWw5LlVyS10iW5lcAX++Xue39UnEhlW0HSaQ5Ariu1xgiL7lRuGyUrMKa8zVQywWAXuZfZooVbPry8qzJ2LibVVqY0n93mswbfbC3mEbXrBI3zsLOcZM+eFURrdTLLTdcmTWoEtvWGNGUDsxQ2/CXWfa8ErYE/oOwlUMoA=="
}

### STATUS 200
GET localhost:8083/api/token/get_user
Content-Type: application/json

{
  "access_token": "YSvsVr73inbzmfS4wJWmWyrx2jZgxTTdPUKZpxFPKF+rz+Nneye5VgNstOHiXn4TCnFLwaDbL/NL9agsq1U2fXalFH5lI5oySL5Ho7oDeVV7QU3xzvrdmjloA3TBpDVzBNVO1U/KimnJiJLXO4Uhe8necstlzuCDHnXeL4rGC+BKH/N0j1x10HNIkJ3hdB3H744tNuY2rdvAnot7Z/BRyNqA8+m7UsgML2lMzZ3wN8E+8lUCq0+seV9X+0k4je1JBAz7OaQV6q3nPUUfoXj5MwVKrJE9TXYtB03eIhnjcJDjkSNAYa8H/jijluTQ+lmebq3X8kEfL3o3rkyeXOiUDSJkNmsvClVEoKMsVaGZZaYnvPX+RELV2nhCTD4b3z8EWsAvTQ5WtQJv2ifD8nqj5zeN8EtDCUjPkxpjIf2jtUjE0UvlOygBu1AVVmm7GnZIRIqxdTQqactrANCESWf5yXI35Cta/9pwhn1VSfENX1s7HOWDtNfr0Psr+XUC4ULzz2VKAI0reMzDW9wR0Sy7ru2bElVF2eLdQ615XU8oa07xYeCk8tzMS4HiB+5NAyJB+5b93g68wunhzKqQ8YKeONRIu1l4JSJ8QccedivjxVRq3BOjmRwVetf3n5FHAhIPx0S2vCxjTXHn+/JDj8hQguFSOl4jKoZZEe1D0xj4KSjLQGGdsV7/AqgURbWAg/BoQhzvjYoAMCorbaNrtDLsRo/yvgSrDOl/cWdla25VNgsGrn83UXl4JC3nlTPMfBsG/WvJedYfBdyRWTUia5sT5C/qaBGkRnWJvZPWNzm9kaV1HMwUEVDO1qX08KsA+jSDvzJnixnsCEb22uDaThk++DkvYa+c/Yb93+GTi8Fc7o77TlgzSrURt2hlrJkjHCjJlh7BTD2mNBjRf2f+"
}

### STATUS 200
POST localhost:8083/api/token/logout
Content-Type: application/json

{
  "access_token": "dSiyp0mbfno/9BlvwxsX6m2Xnoc6nSXuQE5OTtbkZ2rr26CkKsU9yk7XJnfsAmrPRRj9sr2Hhq0J2+g+2EGBOUYesaYiZ/0v/7qmsi6jK5M7nE2A+jPZg+MXW7TGi7em73KTVFZGYZ21nhc4URRfnZ1gqtcUBtTGXG9bHFOjsVwSV1b661cUS0w2Kd6fPg4CqLbViMLN2WIiOixcNq95tHAvZrVjOmjtywQXSh0V3XOOdvCwPBm3y8RKJ70W0M11MitHqQvhXkRzZykdAYoUtlWjEYI7wWU5c+fmtDLohH7fK/TbukXJn5VEPlWfXYTAs3oRrbt+FQF3VY1wy1jVS7Q/PvXdzsy1R6DSF7h2HEFS+evrryNsEdazObsBWTJ3w40o0QFOwj9aZJtoz5jMWUPCWYNFhiI8Nd3vJwKCaiQNQvtWmRvaIeAKYCPtdyCZfS7bI4cuzPsFNcUi93qwtSR0+UBXAv5w7l7yvlX+G9pff88TTGUynjex/y3eRvbZdExzEE0XQrRawbxCHHsZ1B1fevQk8AdwL/1bYzcroNuluyleomZQHh2lQ/ECvDLxlD7/K5NF7fgSclIHSfb4gFkbd2fos0e8zVAk45V2SOeor0uXdtF1WedcN4TKCNj+zBjlneCd0svPEYLMWM9SgivlumpqHK+pTRWyg7RhUAssPZ9RgGpIAGf2fA6e8aMME5h9ozVkdkugO/yoFCvgyteCl2/KVBgs+j5i9odSdJYHwvXLhzWZAA3JIwpZVTV8yR8N889a7SJVpI6zR/woAa8XSvKy9KG13G2lI4npqP3dNfjbsNOOFCRU9Wrd3W2N4OpmoFVDCJROFpvFTkzgyOiYCxh1sGLMi/nQ+6fq9ATzF4iNOn+lSYzY1mO6I2AuibJLBLWYBqkdI8GH"}
