http:
 port: 8083

postgres:
 host: "localhost" #localhost postgres
 port: 5432
 user: "postgres"
 password: "4650"
 dbname: "postgres"
 sslmode: "disable"

tarantool:
 host: "localhost" #localhost tarantool
 port: 3301
 user: "user"
 password: "pass"

redis:
 host: "localhost" #localhost redis
 port: 6379
 user: "user"
 password: "pass"